# -*- coding: utf-8 -*-
"""prueba_tecnica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YQfg-_oJNYROnKP8K_gnJejUsr32SQjp
"""

def ordenar_numeros(lista):

    # Verificar si la lista está vacía
    if not lista:
        print("Lista vacía")
        return []

    # Inicializar listas para números pares e impares
    pares = []
    impares = []

    # Analizar la lista de entrada
    for elemento in lista:

        # Verificar si el elemento es una lista, tupla o diccionario
        if isinstance(elemento, (list, tuple, dict)):
            print("Elemento no numérico ignorado:", elemento)
            continue

        # Intentar convertir el elemento a un entero
        try:
            num = int(elemento)
        except ValueError:
            print("Elemento no numérico ignorado:", elemento)
            continue

        # Separar números pares e impares y agregarlos a las listas correspondientes
        if num %   2 ==   0:
            pares.append(num)
        else:
            impares.append(num)

    # Ordenar ambas listas
    pares.sort()
    impares.sort()

    # Concatenar y devolver la lista final
    return pares + impares

# Lista de ejemplo
numeros = [2, 8, 4, 'e', -5, 9, 15, (12,2),'a5', [5,6,48,7], 89, {'b':12,'s':84}, 78]

numeros_ordenados = ordenar_numeros(numeros)

if numeros:
  print(f'\nLista final ordenada: {numeros_ordenados}')